spring:
  application:
    name: orderservice

  datasource:
    url: jdbc:h2:mem:inventory
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

resilience4j:

  # =========================
  # Circuit Breaker
  # =========================
  circuitbreaker:
    instances:
      orderservice:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  # =========================
  # Retry
  # =========================
  retry:
    instances:
      orderservice:
        maxAttempts: 3
        waitDuration: 1s

  # =========================
  # Rate Limiter
  # =========================
  ratelimiter:
    instances:
      orderservice:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 2s

  # =========================
  # Bulkhead
  # =========================
  # bulkhead:
  #   instances:
  #     orderservice:
  #       maxConcurrentCalls: 20
  #       maxWaitDuration: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
my:
  variable: or-var-dev
